cc_binary(
  name = "main",
  srcs = [
    "main.cc"
  ],
  deps = [
    "//demo-01:main_lib"
  ]
)

cc_library(
  name = "main_lib",
  srcs = [
    "circle.cc",
    "rectangle.cc"
  ],
  deps = []
)
